kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume
  namespace: wso2
  labels:
    type: local
    app: postgres
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: wso2
  labels:
    app: postgres
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi